spring:
  application:
    name: goalmate
  config:
    import:
      - optional:file:.env[.properties]
  profiles:
    active: local
    
server:
  tomcat:
    max-connections: 20000
    threads:
      max: 600
      min-spare: 100
  port: 8080
