spring:
  application:
    name: goalmate
  config:
    import:
      - optional:classpath:env.yaml
  profiles:
    active: local

server:
  tomcat:
    max-connections: 20000
    threads:
      max: 600
      min-spare: 100
  port: 8080
---
spring.config.activate.on-profile: local

spring:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        show_sql: true
      hibernate.default_batch_fetch_size: 1000
    show-sql: true
    generate-ddl: true
    defer-datasource-initialization: true
    open-in-view: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/goalmate
    username: root
    password: local1234!
  sql:
    init:
      mode: always
      data-locations: classpath:db/data.sql
      #      schema-locations: classpath:db/schema.sql
  data:
    redis:
      host: ${redis.host}
      port: ${redis.port}

---
spring.config.activate.on-profile: dev

spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        show_sql: true
      hibernate.default_batch_fetch_size: 1000
    show-sql: true
    generate-ddl: true
    defer-datasource-initialization: true
    open-in-view: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${aws.rds.url}
    username: ${aws.rds.username}
    password: ${aws.rds.password}
  sql:
    init:
      mode: never
      data-locations: classpath:db/data.sql
      #      schema-locations: classpath:db/schema.sql
  data:
    redis:
      host: ${redis.host}
      port: ${redis.port}
