spring:
  application:
    name: goalmate
  lifecycle:
    timeout-per-shutdown-phase: 30s
  config:
    import:
      - classpath:/yaml/
  profiles:
    active: local
  servlet:
    multipart:
      enabled: true  # 멀티파트 업로드 지원 여부 (default: true)
      file-size-threshold: 0B  # 메모리에 저장하는 최소 크기 (default: 0B)
      location: /tmp/goalmate  # 업로드된 파일이 임시로 저장되는 위치
      max-file-size: 100MB  # 개별 파일의 최대 크기
      max-request-size: 100MB  # 전체 요청의 최대 크기

server:
  tomcat:
    max-connections: 20000
    threads:
      max: 600
      min-spare: 100
  port: 8080
  shutdown: graceful
management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
