spring.profiles.active: local

spring:
  config:
    import:
      - optional:file:.env[.properties]
server:
  tomcat:
    max-connections: 20000
    threads:
      max: 600
      min-spare: 100
  port: 8080
