services:
  goalmate:
    image: dhxl50/goalmate:latest  # 빌드한 Docker 이미지
    ports:
      - "80:8080"                 # 호스트 포트 80 -> 컨테이너 포트 8080 매핑
    deploy:
      replicas: 2                 # 컨테이너 2개 실행 (분산 배치)
      update_config:
        parallelism: 1            # 한 번에 하나의 컨테이너 업데이트
        delay: 10s                # 업데이트 사이 간격
      restart_policy:
        condition: on-failure     # 실패 시 재시작
        max_attempts: 5          # 최대 재시작 횟수
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/swagger-ui/index.html" ]
      interval: 30s
      timeout: 10s
      retries: 3

  redis:
    image: redis:latest
    ports:
      - "6379:6379"               # 기본 Redis 포트 매핑
    deploy:
      replicas: 1                 # 단일 컨테이너 배포 (필요에 따라 확장 가능)
      restart_policy:
        condition: on-failure     # 실패 시 재시작
